### ISSUE TITLE
Toolbox: Structure spawner 

### ISSUE THREAD

**Issue by Rinju99** [Terasology/StructureTemplates#28]
**Structure Spawner** from Toolbox is not working

**Comment by Rinju99** [comment]
![Annotation 2019-04-21 160815](https://user-images.githubusercontent.com/47399602/56475579-b39b3c80-644f-11e9-885e-7ed9e8e1af8f.png)

**Comment by Cervator** [comment]
Same comment as in #29 :-)

In general you might want to hop on chat and confirm something as an issue or a usage problem before taking the trouble to submit an issue. Still really appreciate the thought though! We do need more bug reports! This just happily isn't a bug :-)
