### ISSUE TITLE
Toolbox: Structure Templates is disabled

### ISSUE THREAD

**Issue by Rinju99** [Terasology/StructureTemplates#29]
`Structure Templates` from Toolbox is not working. When you choose Structure templates, the` get item` does not activate.

**Comment by Rinju99** [comment]
![Annotation 2019-04-21 160530](https://user-images.githubusercontent.com/47399602/56475552-5c956780-644f-11e9-900a-9b814a7059de.png)

**Comment by Cervator** [comment]
Hey there. So you need to actually have STs available to get. In this case you don't seem to have any available in the active set of modules.

If you run the game with GooeysQuests or something active those two bottom items in the list will be expandable and contain lots of items. Those are the ones you can get with the button :-)

There might be a small chance the module isn't building right so the assets aren't available yet - but in that case I wouldn't expect you to be able to get the toolbox itself.

I coincidentally tested that yesterday so I'm pretty confident this isn't a bug. Closing as a non-issue - try it out with GQ or come say hi on chat!
