### ISSUE TITLE
Option to ignore blocks

### ISSUE THREAD

**Issue by skaldarnar** [Terasology/StructureTemplates#3]
Add an option to ignore `air` blocks when spawing a structure. Could be useful for overhanging structures, or when some building should be placed on any ground.

**Comment by flo** [comment]
@skaldarnar Not sure what you mean with "ignoring"? Structure templates don't care about any blocks being present. You have to add conditions manually to prevent structures from being placed anywhere.

**Comment by skaldarnar** [comment]
I neither want to prevent structures from spawning, nor do I want to care about blocks present. With "ignore air blocks" I mean to not actually place an air block when it is encountered in the template, but just do nothing for this position. 
For instance, when you have a portal frame and place it against a wall, the frame will be filled with the wall's blocks (instead of "cutting out" the inner part).
